Repository prasanth5205/spark1_repo, pull requests merged in 2018-03, with the labels that each got.

#16 GitHub/thursday
  welcome.txt
Labels: bug

#18 Wednesday pull request
  Sampl
Labels: bug, help wanted

#20 Main pull request
  Sampl
  TestCaseRavi
  hasiais
  hello.txt
Labels: duplicate, question
